Maxon:
  config_run_sdo_verify_timeout: 50000
  print_debug_messages: true
  use_raw_commands: false
  drive_state_change_min_timeout: 2000
  drive_state_change_max_timeout: 1000000
  min_number_of_successful_target_state_readings: 5

Reading:
  force_append_equal_error: true
  force_append_equal_fault: false
  error_storage_capacity: 100
  fault_storage_capacity: 100

Hardware:
  mode_of_operation:
  - CyclicSynchronousTorqueMode
  - CyclicSynchronousPositionMode
  - CyclicSynchronousVelocityMode
  position_encoder_resolution: 4096
  gear_ratio: [9,169]
  motor_constant: 1.0
  working_voltage: 24
  pole_pairs: 7
  speed_constant: 26
  torque_constant: 0.047756
  max_current: 15.421
  nominal_current: 5.14
  min_position: 0
  max_position: 0 # Disable checks
  max_profile_velocity: 500
  quick_stop_decel: 1000
  profile_decel: 1000
  follow_error_window: 4294967295
  motor_rated_torque: 0.258
  current_p_gain: 0.382429 #8.426858
  current_i_gain: 760.955 #10699.972
  position_p_gain: 16.984530
  position_i_gain: 347.798341
  position_d_gain: 0.271994 #0.099505
  velocity_p_gain: 0.258725 #0.119284
  velocity_i_gain: 11.208479 #9.654194
