ethercat_master:
  time_step:                          0.005
  update_rate_too_low_warn_threshold: 50

ethercat_devices:
  - type:               Maxon
    name:               Paretic
    configuration_file: plantar.yaml
    ethercat_bus:       enp2s0
    ethercat_address:   2

  - type:               Maxon
    name:               NonParetic
    configuration_file: dorsi.yaml
    ethercat_bus:       enp2s0
    ethercat_address:   1

